/**
 * SQLite adapter (sql.js — pure JS, no native build).
 *
 * Tables stored here:
 *   - audit_logs  (write-heavy, no clinical JOINs needed)
 *   - alerts      (generated by risk engine, read by dashboard)
 *
 * Exposes the same .execute(sql, params) interface as mysql2/promise pool.
 */
const initSqlJs = require('sql.js');
const fs = require('fs');
const path = require('path');

const DB_PATH = path.join(__dirname, '..', '..', 'data', 'rmdp_local.sqlite');

const dataDir = path.dirname(DB_PATH);
if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true });

let _db = null;

async function getDb() {
  if (_db) return _db;
  const SQL = await initSqlJs();
  if (fs.existsSync(DB_PATH)) {
    _db = new SQL.Database(fs.readFileSync(DB_PATH));
  } else {
    _db = new SQL.Database();
    _initSchema(_db);
    _persist(_db);
  }
  return _db;
}

function _persist(db) {
  fs.writeFileSync(DB_PATH, Buffer.from(db.export()));
}

function _initSchema(db) {
  db.run(`
    CREATE TABLE IF NOT EXISTS audit_logs (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id INTEGER,
      facility_id INTEGER,
      action TEXT NOT NULL,
      entity_type TEXT,
      entity_id INTEGER,
      details TEXT,
      ip_address TEXT,
      created_at TEXT DEFAULT (datetime('now'))
    );

    CREATE TABLE IF NOT EXISTS alerts (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      pregnancy_id INTEGER NOT NULL,
      facility_id INTEGER NOT NULL,
      alert_type TEXT NOT NULL,
      severity TEXT NOT NULL,
      title TEXT NOT NULL,
      message TEXT,
      recommended_actions TEXT,
      status TEXT DEFAULT 'active',
      created_by INTEGER,
      created_at TEXT DEFAULT (datetime('now')),
      resolved_at TEXT
    );

    CREATE INDEX IF NOT EXISTS idx_alerts_pregnancy ON alerts(pregnancy_id);
    CREATE INDEX IF NOT EXISTS idx_alerts_facility  ON alerts(facility_id);
    CREATE INDEX IF NOT EXISTS idx_alerts_status    ON alerts(status);
    CREATE INDEX IF NOT EXISTS idx_audit_user       ON audit_logs(user_id);
    CREATE INDEX IF NOT EXISTS idx_audit_entity     ON audit_logs(entity_type, entity_id);
  `);
}

/**
 * execute(sql, params) → Promise<[rows|meta]>
 * Matches mysql2/promise pool.execute() return shape.
 */
async function execute(sql, params = []) {
  const db = await getDb();
  const upper = sql.trim().toUpperCase();

  if (upper.startsWith('SELECT') || upper.startsWith('WITH')) {
    const stmt = db.prepare(sql);
    stmt.bind(params.map(_coerce));
    const rows = [];
    while (stmt.step()) rows.push(stmt.getAsObject());
    stmt.free();
    return [rows];
  }

  db.run(sql, params.map(_coerce));
  _persist(db);

  const insertId = db.exec('SELECT last_insert_rowid()')[0]?.values[0][0] ?? 0;
  return [{ insertId, affectedRows: db.getRowsModified() }];
}

function _coerce(v) {
  if (v === undefined) return null;
  if (typeof v === 'object' && v !== null) return JSON.stringify(v);
  return v;
}

module.exports = { execute };
